name: Build SimpleVoiceChatAEC

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu indir
        uses: actions/checkout@v4

      - name: ZIP dosyasını çıkar
        run: |
          unzip -q SimpleVoiceChatAEC-1.0.0-source.zip -d extracted

      - name: Java 25 kur
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Gradle Wrapper'ı düzelt
        working-directory: extracted/SimpleVoiceChatAEC
        run: |
          chmod +x gradlew
          sed -i 's/DEFAULT_JVM_OPTS=.*/DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"/' gradlew
          grep DEFAULT_JVM_OPTS gradlew

      - name: Java sürümünü kontrol et
        run: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Gradle sürümünü kontrol et
        working-directory: extracted/SimpleVoiceChatAEC
        run: |
          ./gradlew --version

      - name: Build
        working-directory: extracted/SimpleVoiceChatAEC
        run: |
          ./gradlew build --no-daemon --stacktrace

      - name: JAR dosyasını yükle
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SimpleVoiceChatAEC
          path: extracted/SimpleVoiceChatAEC/build/libs/*.jar
          if-no-files-found: error
